/**
 * GENERATED BOARDS — do not hand-edit.
 *
 * Every board here was produced by a constructive generator (a guaranteed
 * solution path is built first, then mirrors are scrambled) and then
 * re-verified independently by the BFS solver in src/game/analysis.ts:
 * the recorded par equals the solver's exhaustive minimum-move count and
 * `solutions` is its optimal-solution count. Regenerating is the only
 * supported way to change them; scripts/validate-levels.ts re-checks every
 * board on every run.
 */
import type { Board, Piece } from "./types";

let uid = 0;
const mk = (p: Omit<Piece, "id">): Piece => ({ id: `g${++uid}`, ...p });

interface GenSpec {
  width: number;
  height: number;
  cells: Array<[string, Omit<Piece, "id">]>;
  tray?: Array<Omit<Piece, "id">>;
}

const gen = (s: GenSpec): Board => ({
  width: s.width,
  height: s.height,
  cells: Object.fromEntries(s.cells.map(([k, p]) => [k, mk(p)])),
  tray: (s.tray ?? []).map(mk),
});

/** id -> solver-verified board. */
export const GENERATED: Record<string, Board> = {
  "1-4": gen({
    width: 7,
    height: 8,
    cells: [
      ["4,0", { kind: "mirror", rot: 0 }],
      ["4,4", { kind: "mirror", rot: 0 }],
      ["6,4", { kind: "mirror", rot: 1 }],
      ["6,7", { kind: "target", rot: 0, color: 7, fixed: true }],
      ["0,0", { kind: "emitter", rot: 1, color: 7, fixed: true }],
    ],
  }),
  "1-5": gen({
    width: 5,
    height: 7,
    cells: [
      ["0,6", { kind: "mirror", rot: 0 }],
      ["0,3", { kind: "mirror", rot: 1 }],
      ["4,3", { kind: "mirror", rot: 0 }],
      ["4,2", { kind: "target", rot: 0, color: 7, fixed: true }],
      ["4,6", { kind: "emitter", rot: 3, color: 7, fixed: true }],
      ["1,5", { kind: "wall", rot: 0, fixed: true }],
      ["3,2", { kind: "wall", rot: 0, fixed: true }],
    ],
  }),
  "1-6": gen({
    width: 6,
    height: 7,
    cells: [
      ["4,1", { kind: "mirror", rot: 0 }],
      ["4,5", { kind: "mirror", rot: 0 }],
      ["0,2", { kind: "target", rot: 0, color: 7, fixed: true }],
      ["0,1", { kind: "emitter", rot: 1, color: 7, fixed: true }],
    ],
    tray: [
      { kind: "mirror", rot: 1 },
    ],
  }),
  "1-7": gen({
    width: 8,
    height: 7,
    cells: [
      ["2,2", { kind: "mirror", rot: 0 }],
      ["2,5", { kind: "mirror", rot: 0 }],
      ["6,5", { kind: "mirror", rot: 1 }],
      ["6,1", { kind: "target", rot: 0, color: 7, fixed: true }],
      ["0,2", { kind: "emitter", rot: 1, color: 7, fixed: true }],
      ["0,3", { kind: "wall", rot: 0, fixed: true }],
      ["1,4", { kind: "wall", rot: 0, fixed: true }],
    ],
  }),
  "1-8": gen({
    width: 7,
    height: 9,
    cells: [
      ["4,4", { kind: "mirror", rot: 1 }],
      ["4,2", { kind: "mirror", rot: 0 }],
      ["0,1", { kind: "target", rot: 0, color: 7, fixed: true }],
      ["0,4", { kind: "emitter", rot: 1, color: 7, fixed: true }],
    ],
    tray: [
      { kind: "mirror", rot: 1 },
    ],
  }),
  "2-4": gen({
    width: 8,
    height: 8,
    cells: [
      ["5,5", { kind: "splitter", rot: 1, fixed: true }],
      ["3,5", { kind: "mirror", rot: 0 }],
      ["3,1", { kind: "target", rot: 0, color: 7, fixed: true }],
      ["5,2", { kind: "mirror", rot: 1 }],
      ["7,2", { kind: "mirror", rot: 1 }],
      ["7,4", { kind: "target", rot: 0, color: 7, fixed: true }],
      ["7,5", { kind: "emitter", rot: 3, color: 7, fixed: true }],
    ],
  }),
  "2-5": gen({
    width: 8,
    height: 7,
    cells: [
      ["2,6", { kind: "splitter", rot: 0, fixed: true }],
      ["3,6", { kind: "filter", rot: 0, color: 4, fixed: true }],
      ["6,6", { kind: "mirror", rot: 1 }],
      ["6,3", { kind: "target", rot: 0, color: 4, fixed: true }],
      ["2,4", { kind: "filter", rot: 0, color: 1, fixed: true }],
      ["2,0", { kind: "mirror", rot: 1 }],
      ["6,0", { kind: "target", rot: 0, color: 1, fixed: true }],
      ["0,6", { kind: "emitter", rot: 1, color: 7, fixed: true }],
    ],
  }),
  "2-6": gen({
    width: 9,
    height: 9,
    cells: [
      ["6,5", { kind: "splitter", rot: 1, fixed: true }],
      ["4,5", { kind: "filter", rot: 0, color: 4, fixed: true }],
      ["0,5", { kind: "mirror", rot: 1 }],
      ["0,1", { kind: "mirror", rot: 1 }],
      ["4,1", { kind: "target", rot: 0, color: 4, fixed: true }],
      ["6,4", { kind: "filter", rot: 0, color: 2, fixed: true }],
      ["6,2", { kind: "mirror", rot: 0 }],
      ["3,2", { kind: "mirror", rot: 1 }],
      ["3,4", { kind: "target", rot: 0, color: 2, fixed: true }],
      ["8,5", { kind: "emitter", rot: 3, color: 7, fixed: true }],
    ],
  }),
  "2-7": gen({
    width: 8,
    height: 7,
    cells: [
      ["3,2", { kind: "prism", rot: 0, fixed: true }],
      ["7,2", { kind: "mirror", rot: 1 }],
      ["7,0", { kind: "target", rot: 0, color: 1, fixed: true }],
      ["3,0", { kind: "mirror", rot: 0 }],
      ["6,0", { kind: "target", rot: 0, color: 2, fixed: true }],
      ["3,6", { kind: "mirror", rot: 0 }],
      ["5,6", { kind: "target", rot: 0, color: 4, fixed: true }],
      ["0,2", { kind: "emitter", rot: 1, color: 7, fixed: true }],
    ],
  }),
  "2-8": gen({
    width: 7,
    height: 7,
    cells: [
      ["2,5", { kind: "prism", rot: 0, fixed: true }],
      ["4,5", { kind: "target", rot: 0, color: 1, fixed: true }],
      ["2,2", { kind: "mirror", rot: 0 }],
      ["6,2", { kind: "mirror", rot: 0 }],
      ["6,6", { kind: "target", rot: 0, color: 2, fixed: true }],
      ["2,6", { kind: "mirror", rot: 0 }],
      ["5,6", { kind: "mirror", rot: 1 }],
      ["5,4", { kind: "target", rot: 0, color: 4, fixed: true }],
      ["0,5", { kind: "emitter", rot: 1, color: 7, fixed: true }],
    ],
  }),
  "2-9": gen({
    width: 9,
    height: 9,
    cells: [
      ["4,6", { kind: "mirror", rot: 0 }],
      ["4,8", { kind: "mirror", rot: 1 }],
      ["2,8", { kind: "mirror", rot: 0 }],
      ["3,4", { kind: "target", rot: 0, color: 7, fixed: true }],
      ["8,6", { kind: "emitter", rot: 3, color: 7, fixed: true }],
      ["0,1", { kind: "wall", rot: 0, fixed: true }],
    ],
    tray: [
      { kind: "mirror", rot: 0 },
    ],
  }),
  "3-4": gen({
    width: 8,
    height: 7,
    cells: [
      ["3,2", { kind: "mirror", rot: 1 }],
      ["3,5", { kind: "mirror", rot: 0 }],
      ["7,5", { kind: "target", rot: 0, color: 7, fixed: true }],
      ["4,1", { kind: "mirror", rot: 0 }],
      ["4,0", { kind: "mirror", rot: 0 }],
      ["1,0", { kind: "target", rot: 0, color: 7, fixed: true }],
      ["0,1", { kind: "emitter", rot: 1, color: 7, fixed: true }],
      ["7,2", { kind: "emitter", rot: 3, color: 7, fixed: true }],
    ],
  }),
  "3-5": gen({
    width: 8,
    height: 7,
    cells: [
      ["3,4", { kind: "splitter", rot: 1, fixed: true }],
      ["4,4", { kind: "mirror", rot: 1 }],
      ["4,0", { kind: "mirror", rot: 0 }],
      ["1,0", { kind: "target", rot: 0, color: 7, fixed: true }],
      ["3,6", { kind: "mirror", rot: 1 }],
      ["7,6", { kind: "mirror", rot: 1 }],
      ["7,2", { kind: "target", rot: 0, color: 7, fixed: true }],
      ["0,4", { kind: "emitter", rot: 1, color: 7, fixed: true }],
      ["6,3", { kind: "wall", rot: 0, fixed: true }],
    ],
  }),
  "3-6": gen({
    width: 9,
    height: 9,
    cells: [
      ["7,4", { kind: "mirror", rot: 0 }],
      ["7,6", { kind: "mirror", rot: 1 }],
      ["3,6", { kind: "mirror", rot: 0 }],
      ["4,3", { kind: "target", rot: 0, color: 7, fixed: true }],
      ["8,4", { kind: "emitter", rot: 3, color: 7, fixed: true }],
    ],
    tray: [
      { kind: "mirror", rot: 0 },
    ],
  }),
  "3-7": gen({
    width: 9,
    height: 8,
    cells: [
      ["2,7", { kind: "splitter", rot: 0, fixed: true }],
      ["3,7", { kind: "mirror", rot: 1 }],
      ["3,5", { kind: "mirror", rot: 0 }],
      ["2,5", { kind: "target", rot: 0, color: 7, fixed: true }],
      ["2,6", { kind: "mirror", rot: 0 }],
      ["1,6", { kind: "mirror", rot: 0 }],
      ["1,4", { kind: "target", rot: 0, color: 7, fixed: true }],
      ["0,7", { kind: "emitter", rot: 1, color: 7, fixed: true }],
    ],
  }),
  "3-8": gen({
    width: 9,
    height: 9,
    cells: [
      ["3,1", { kind: "splitter", rot: 1, fixed: true }],
      ["4,1", { kind: "filter", rot: 0, color: 4, fixed: true }],
      ["8,1", { kind: "mirror", rot: 0 }],
      ["8,5", { kind: "mirror", rot: 1 }],
      ["5,5", { kind: "target", rot: 0, color: 4, fixed: true }],
      ["3,3", { kind: "filter", rot: 0, color: 2, fixed: true }],
      ["3,6", { kind: "mirror", rot: 1 }],
      ["0,6", { kind: "mirror", rot: 1 }],
      ["0,8", { kind: "target", rot: 0, color: 2, fixed: true }],
      ["0,1", { kind: "emitter", rot: 1, color: 7, fixed: true }],
      ["1,7", { kind: "wall", rot: 0, fixed: true }],
      ["6,3", { kind: "wall", rot: 0, fixed: true }],
    ],
  }),
  "3-9": gen({
    width: 9,
    height: 9,
    cells: [
      ["5,7", { kind: "mirror", rot: 0 }],
      ["5,6", { kind: "mirror", rot: 1 }],
      ["1,6", { kind: "target", rot: 0, color: 7, fixed: true }],
      ["4,0", { kind: "mirror", rot: 0 }],
      ["4,4", { kind: "mirror", rot: 1 }],
      ["0,4", { kind: "mirror", rot: 1 }],
      ["0,8", { kind: "target", rot: 0, color: 7, fixed: true }],
      ["0,0", { kind: "emitter", rot: 1, color: 7, fixed: true }],
      ["8,7", { kind: "emitter", rot: 3, color: 7, fixed: true }],
      ["6,4", { kind: "wall", rot: 0, fixed: true }],
    ],
  }),
  "4-4": gen({
    width: 9,
    height: 8,
    cells: [
      ["3,0", { kind: "mirror", rot: 0 }],
      ["3,3", { kind: "mirror", rot: 1 }],
      ["7,3", { kind: "mirror", rot: 0 }],
      ["3,7", { kind: "target", rot: 0, color: 7, fixed: true }],
      ["0,0", { kind: "emitter", rot: 1, color: 7, fixed: true }],
      ["8,6", { kind: "wall", rot: 0, fixed: true }],
    ],
    tray: [
      { kind: "mirror", rot: 0 },
    ],
  }),
  "4-5": gen({
    width: 7,
    height: 9,
    cells: [
      ["2,7", { kind: "mirror", rot: 0 }],
      ["2,5", { kind: "mirror", rot: 1 }],
      ["6,5", { kind: "mirror", rot: 1 }],
      ["2,2", { kind: "target", rot: 0, color: 7, fixed: true }],
      ["6,7", { kind: "emitter", rot: 3, color: 7, fixed: true }],
    ],
    tray: [
      { kind: "mirror", rot: 1 },
    ],
  }),
  "4-6": gen({
    width: 9,
    height: 9,
    cells: [
      ["4,8", { kind: "mirror", rot: 0 }],
      ["4,7", { kind: "mirror", rot: 0 }],
      ["0,7", { kind: "mirror", rot: 0 }],
      ["4,3", { kind: "target", rot: 0, color: 7, fixed: true }],
      ["8,8", { kind: "emitter", rot: 3, color: 7, fixed: true }],
      ["2,0", { kind: "wall", rot: 0, fixed: true }],
      ["7,3", { kind: "wall", rot: 0, fixed: true }],
    ],
    tray: [
      { kind: "mirror", rot: 0 },
    ],
  }),
  "4-7": gen({
    width: 9,
    height: 8,
    cells: [
      ["6,7", { kind: "splitter", rot: 1, fixed: true }],
      ["2,7", { kind: "mirror", rot: 0 }],
      ["2,5", { kind: "mirror", rot: 1 }],
      ["3,5", { kind: "target", rot: 0, color: 7, fixed: true }],
      ["6,3", { kind: "mirror", rot: 0 }],
      ["8,3", { kind: "mirror", rot: 1 }],
      ["8,0", { kind: "mirror", rot: 0 }],
      ["4,0", { kind: "target", rot: 0, color: 7, fixed: true }],
      ["8,7", { kind: "emitter", rot: 3, color: 7, fixed: true }],
      ["6,1", { kind: "wall", rot: 0, fixed: true }],
    ],
  }),
  "4-8": gen({
    width: 9,
    height: 9,
    cells: [
      ["3,5", { kind: "splitter", rot: 0, fixed: true }],
      ["7,5", { kind: "mirror", rot: 1 }],
      ["7,1", { kind: "mirror", rot: 0 }],
      ["3,1", { kind: "target", rot: 0, color: 7, fixed: true }],
      ["3,2", { kind: "mirror", rot: 0 }],
      ["0,2", { kind: "mirror", rot: 1 }],
      ["0,4", { kind: "mirror", rot: 0 }],
      ["2,4", { kind: "target", rot: 0, color: 7, fixed: true }],
      ["0,5", { kind: "emitter", rot: 1, color: 7, fixed: true }],
    ],
  }),
  "4-9": gen({
    width: 9,
    height: 8,
    cells: [
      ["4,1", { kind: "mirror", rot: 1 }],
      ["4,4", { kind: "mirror", rot: 0 }],
      ["8,4", { kind: "mirror", rot: 0 }],
      ["4,7", { kind: "target", rot: 0, color: 7, fixed: true }],
      ["8,1", { kind: "emitter", rot: 3, color: 7, fixed: true }],
    ],
    tray: [
      { kind: "mirror", rot: 0 },
    ],
  }),
  "5-2": gen({
    width: 8,
    height: 9,
    cells: [
      ["4,4", { kind: "prism", rot: 0, fixed: true }],
      ["0,4", { kind: "mirror", rot: 1 }],
      ["0,8", { kind: "target", rot: 0, color: 1, fixed: true }],
      ["4,6", { kind: "mirror", rot: 0 }],
      ["6,6", { kind: "mirror", rot: 1 }],
      ["6,5", { kind: "target", rot: 0, color: 2, fixed: true }],
      ["4,0", { kind: "mirror", rot: 0 }],
      ["1,0", { kind: "mirror", rot: 0 }],
      ["1,3", { kind: "target", rot: 0, color: 4, fixed: true }],
      ["7,4", { kind: "emitter", rot: 3, color: 7, fixed: true }],
      ["2,1", { kind: "wall", rot: 0, fixed: true }],
    ],
  }),
  "5-3": gen({
    width: 9,
    height: 9,
    cells: [
      ["5,7", { kind: "splitter", rot: 1, fixed: true }],
      ["4,7", { kind: "filter", rot: 0, color: 2, fixed: true }],
      ["0,7", { kind: "mirror", rot: 0 }],
      ["0,5", { kind: "mirror", rot: 1 }],
      ["3,5", { kind: "target", rot: 0, color: 2, fixed: true }],
      ["5,5", { kind: "filter", rot: 0, color: 4, fixed: true }],
      ["5,1", { kind: "mirror", rot: 0 }],
      ["1,1", { kind: "mirror", rot: 1 }],
      ["1,3", { kind: "target", rot: 0, color: 4, fixed: true }],
      ["8,7", { kind: "emitter", rot: 3, color: 7, fixed: true }],
    ],
  }),
  "5-4": gen({
    width: 9,
    height: 7,
    cells: [
      ["3,4", { kind: "prism", rot: 0, fixed: true }],
      ["4,4", { kind: "mirror", rot: 0 }],
      ["4,5", { kind: "target", rot: 0, color: 1, fixed: true }],
      ["3,0", { kind: "mirror", rot: 1 }],
      ["5,0", { kind: "mirror", rot: 0 }],
      ["5,4", { kind: "mirror", rot: 0 }],
      ["8,4", { kind: "target", rot: 0, color: 2, fixed: true }],
      ["3,5", { kind: "mirror", rot: 1 }],
      ["0,5", { kind: "mirror", rot: 0 }],
      ["0,6", { kind: "target", rot: 0, color: 4, fixed: true }],
      ["0,4", { kind: "emitter", rot: 1, color: 7, fixed: true }],
      ["2,3", { kind: "wall", rot: 0, fixed: true }],
    ],
  }),
  "5-5": gen({
    width: 7,
    height: 8,
    cells: [
      ["3,6", { kind: "splitter", rot: 0, fixed: true }],
      ["6,6", { kind: "mirror", rot: 1 }],
      ["6,3", { kind: "mirror", rot: 0 }],
      ["3,3", { kind: "target", rot: 0, color: 7, fixed: true }],
      ["3,4", { kind: "mirror", rot: 0 }],
      ["0,4", { kind: "mirror", rot: 0 }],
      ["0,1", { kind: "mirror", rot: 1 }],
      ["4,1", { kind: "target", rot: 0, color: 7, fixed: true }],
      ["0,6", { kind: "emitter", rot: 1, color: 7, fixed: true }],
      ["0,5", { kind: "wall", rot: 0, fixed: true }],
    ],
  }),
  "5-6": gen({
    width: 9,
    height: 9,
    cells: [
      ["2,4", { kind: "mirror", rot: 1 }],
      ["2,0", { kind: "mirror", rot: 0 }],
      ["1,0", { kind: "mirror", rot: 0 }],
      ["1,3", { kind: "target", rot: 0, color: 7, fixed: true }],
      ["6,2", { kind: "mirror", rot: 1 }],
      ["6,6", { kind: "mirror", rot: 1 }],
      ["3,6", { kind: "mirror", rot: 0 }],
      ["3,2", { kind: "target", rot: 0, color: 7, fixed: true }],
      ["8,2", { kind: "emitter", rot: 3, color: 7, fixed: true }],
      ["0,4", { kind: "emitter", rot: 1, color: 7, fixed: true }],
    ],
  }),
  "6-1": gen({
    width: 8,
    height: 8,
    cells: [
      ["1,7", { kind: "mirror", rot: 1 }],
      ["1,3", { kind: "mirror", rot: 0 }],
      ["0,3", { kind: "target", rot: 0, color: 7, fixed: true }],
      ["3,7", { kind: "mirror", rot: 0 }],
      ["3,3", { kind: "mirror", rot: 0 }],
      ["6,3", { kind: "target", rot: 0, color: 7, fixed: true }],
      ["7,7", { kind: "emitter", rot: 3, color: 7, fixed: true }],
      ["0,7", { kind: "emitter", rot: 1, color: 7, fixed: true }],
      ["0,0", { kind: "wall", rot: 0, fixed: true }],
      ["5,1", { kind: "wall", rot: 0, fixed: true }],
    ],
  }),
  "6-2": gen({
    width: 9,
    height: 9,
    cells: [
      ["5,5", { kind: "splitter", rot: 1, fixed: true }],
      ["3,5", { kind: "filter", rot: 0, color: 1, fixed: true }],
      ["0,5", { kind: "mirror", rot: 0 }],
      ["0,3", { kind: "mirror", rot: 1 }],
      ["3,3", { kind: "target", rot: 0, color: 1, fixed: true }],
      ["5,3", { kind: "filter", rot: 0, color: 4, fixed: true }],
      ["5,0", { kind: "mirror", rot: 0 }],
      ["6,0", { kind: "mirror", rot: 0 }],
      ["6,2", { kind: "target", rot: 0, color: 4, fixed: true }],
      ["8,5", { kind: "emitter", rot: 3, color: 7, fixed: true }],
      ["3,1", { kind: "wall", rot: 0, fixed: true }],
    ],
  }),
  "6-3": gen({
    width: 7,
    height: 8,
    cells: [
      ["2,5", { kind: "prism", rot: 0, fixed: true }],
      ["6,5", { kind: "mirror", rot: 1 }],
      ["6,4", { kind: "target", rot: 0, color: 1, fixed: true }],
      ["2,1", { kind: "mirror", rot: 0 }],
      ["5,1", { kind: "mirror", rot: 0 }],
      ["5,3", { kind: "target", rot: 0, color: 2, fixed: true }],
      ["2,7", { kind: "mirror", rot: 0 }],
      ["4,7", { kind: "target", rot: 0, color: 4, fixed: true }],
      ["0,5", { kind: "emitter", rot: 1, color: 7, fixed: true }],
    ],
  }),
  "6-4": gen({
    width: 9,
    height: 8,
    cells: [
      ["4,2", { kind: "mirror", rot: 0 }],
      ["4,3", { kind: "mirror", rot: 1 }],
      ["0,3", { kind: "mirror", rot: 1 }],
      ["0,7", { kind: "target", rot: 0, color: 7, fixed: true }],
      ["7,7", { kind: "mirror", rot: 1 }],
      ["7,4", { kind: "mirror", rot: 0 }],
      ["3,4", { kind: "target", rot: 0, color: 7, fixed: true }],
      ["8,7", { kind: "emitter", rot: 3, color: 7, fixed: true }],
      ["0,2", { kind: "emitter", rot: 1, color: 7, fixed: true }],
      ["7,2", { kind: "wall", rot: 0, fixed: true }],
    ],
  }),
  "6-5": gen({
    width: 8,
    height: 9,
    cells: [
      ["2,8", { kind: "splitter", rot: 0, fixed: true }],
      ["3,8", { kind: "filter", rot: 0, color: 4, fixed: true }],
      ["7,8", { kind: "mirror", rot: 1 }],
      ["7,6", { kind: "mirror", rot: 0 }],
      ["3,6", { kind: "target", rot: 0, color: 4, fixed: true }],
      ["2,6", { kind: "filter", rot: 0, color: 2, fixed: true }],
      ["2,4", { kind: "mirror", rot: 1 }],
      ["4,4", { kind: "mirror", rot: 1 }],
      ["4,0", { kind: "target", rot: 0, color: 2, fixed: true }],
      ["0,8", { kind: "emitter", rot: 1, color: 7, fixed: true }],
      ["5,2", { kind: "wall", rot: 0, fixed: true }],
    ],
  }),
  "6-6": gen({
    width: 8,
    height: 9,
    cells: [
      ["2,2", { kind: "splitter", rot: 1, fixed: true }],
      ["6,2", { kind: "mirror", rot: 1 }],
      ["6,1", { kind: "mirror", rot: 0 }],
      ["3,1", { kind: "target", rot: 0, color: 7, fixed: true }],
      ["2,6", { kind: "mirror", rot: 0 }],
      ["6,6", { kind: "mirror", rot: 0 }],
      ["6,8", { kind: "mirror", rot: 1 }],
      ["3,8", { kind: "target", rot: 0, color: 7, fixed: true }],
      ["0,2", { kind: "emitter", rot: 1, color: 7, fixed: true }],
      ["6,0", { kind: "wall", rot: 0, fixed: true }],
    ],
  }),
  "7-1": gen({
    width: 7,
    height: 7,
    cells: [
      ["4,3", { kind: "splitter", rot: 1, fixed: true }],
      ["0,3", { kind: "mirror", rot: 1 }],
      ["0,5", { kind: "mirror", rot: 0 }],
      ["4,5", { kind: "target", rot: 0, color: 7, fixed: true }],
      ["4,2", { kind: "mirror", rot: 0 }],
      ["0,2", { kind: "mirror", rot: 0 }],
      ["0,0", { kind: "mirror", rot: 1 }],
      ["4,0", { kind: "target", rot: 0, color: 7, fixed: true }],
      ["6,3", { kind: "emitter", rot: 3, color: 7, fixed: true }],
    ],
  }),
  "7-2": gen({
    width: 9,
    height: 8,
    cells: [
      ["5,5", { kind: "mirror", rot: 0 }],
      ["5,1", { kind: "mirror", rot: 1 }],
      ["8,1", { kind: "mirror", rot: 1 }],
      ["8,4", { kind: "target", rot: 0, color: 7, fixed: true }],
      ["3,2", { kind: "mirror", rot: 0 }],
      ["3,3", { kind: "mirror", rot: 1 }],
      ["1,3", { kind: "mirror", rot: 1 }],
      ["1,7", { kind: "target", rot: 0, color: 7, fixed: true }],
      ["0,2", { kind: "emitter", rot: 1, color: 7, fixed: true }],
      ["8,5", { kind: "emitter", rot: 3, color: 7, fixed: true }],
      ["3,1", { kind: "wall", rot: 0, fixed: true }],
      ["6,4", { kind: "wall", rot: 0, fixed: true }],
    ],
  }),
  "7-3": gen({
    width: 8,
    height: 9,
    cells: [
      ["2,4", { kind: "prism", rot: 0, fixed: true }],
      ["5,4", { kind: "mirror", rot: 1 }],
      ["5,1", { kind: "target", rot: 0, color: 1, fixed: true }],
      ["2,2", { kind: "mirror", rot: 0 }],
      ["0,2", { kind: "mirror", rot: 0 }],
      ["0,0", { kind: "mirror", rot: 1 }],
      ["3,0", { kind: "target", rot: 0, color: 2, fixed: true }],
      ["2,5", { kind: "mirror", rot: 0 }],
      ["6,5", { kind: "mirror", rot: 0 }],
      ["6,4", { kind: "target", rot: 0, color: 4, fixed: true }],
      ["0,4", { kind: "emitter", rot: 1, color: 7, fixed: true }],
    ],
  }),
  "7-4": gen({
    width: 9,
    height: 9,
    cells: [
      ["5,1", { kind: "mirror", rot: 1 }],
      ["5,5", { kind: "mirror", rot: 0 }],
      ["8,5", { kind: "mirror", rot: 1 }],
      ["8,2", { kind: "target", rot: 0, color: 7, fixed: true }],
      ["1,3", { kind: "mirror", rot: 0 }],
      ["1,7", { kind: "mirror", rot: 0 }],
      ["5,7", { kind: "mirror", rot: 1 }],
      ["5,6", { kind: "target", rot: 0, color: 7, fixed: true }],
      ["0,3", { kind: "emitter", rot: 1, color: 7, fixed: true }],
      ["8,1", { kind: "emitter", rot: 3, color: 7, fixed: true }],
      ["2,5", { kind: "wall", rot: 0, fixed: true }],
      ["4,0", { kind: "wall", rot: 0, fixed: true }],
    ],
  }),
  "7-5": gen({
    width: 8,
    height: 9,
    cells: [
      ["4,3", { kind: "prism", rot: 0, fixed: true }],
      ["0,3", { kind: "mirror", rot: 1 }],
      ["0,7", { kind: "target", rot: 0, color: 1, fixed: true }],
      ["4,6", { kind: "mirror", rot: 1 }],
      ["3,6", { kind: "mirror", rot: 1 }],
      ["3,7", { kind: "mirror", rot: 0 }],
      ["6,7", { kind: "target", rot: 0, color: 2, fixed: true }],
      ["4,1", { kind: "mirror", rot: 1 }],
      ["7,1", { kind: "mirror", rot: 1 }],
      ["7,0", { kind: "mirror", rot: 1 }],
      ["4,0", { kind: "target", rot: 0, color: 4, fixed: true }],
      ["7,3", { kind: "emitter", rot: 3, color: 7, fixed: true }],
      ["2,1", { kind: "wall", rot: 0, fixed: true }],
    ],
  }),
  "7-6": gen({
    width: 9,
    height: 9,
    cells: [
      ["5,4", { kind: "splitter", rot: 1, fixed: true }],
      ["4,4", { kind: "mirror", rot: 1 }],
      ["4,7", { kind: "mirror", rot: 1 }],
      ["0,7", { kind: "target", rot: 0, color: 7, fixed: true }],
      ["5,0", { kind: "mirror", rot: 0 }],
      ["1,0", { kind: "mirror", rot: 1 }],
      ["1,3", { kind: "mirror", rot: 0 }],
      ["3,3", { kind: "target", rot: 0, color: 7, fixed: true }],
      ["8,4", { kind: "emitter", rot: 3, color: 7, fixed: true }],
      ["3,4", { kind: "wall", rot: 0, fixed: true }],
    ],
  }),
  "7-7": gen({
    width: 9,
    height: 7,
    cells: [
      ["3,2", { kind: "prism", rot: 0, fixed: true }],
      ["7,2", { kind: "mirror", rot: 0 }],
      ["7,6", { kind: "target", rot: 0, color: 1, fixed: true }],
      ["3,0", { kind: "mirror", rot: 1 }],
      ["7,0", { kind: "mirror", rot: 0 }],
      ["7,1", { kind: "mirror", rot: 1 }],
      ["6,1", { kind: "target", rot: 0, color: 2, fixed: true }],
      ["3,3", { kind: "mirror", rot: 0 }],
      ["6,3", { kind: "mirror", rot: 0 }],
      ["6,6", { kind: "mirror", rot: 1 }],
      ["2,6", { kind: "target", rot: 0, color: 4, fixed: true }],
      ["0,2", { kind: "emitter", rot: 1, color: 7, fixed: true }],
    ],
  }),
  "7-8": gen({
    width: 8,
    height: 9,
    cells: [
      ["4,3", { kind: "prism", rot: 0, fixed: true }],
      ["3,3", { kind: "mirror", rot: 0 }],
      ["3,2", { kind: "mirror", rot: 0 }],
      ["2,2", { kind: "target", rot: 0, color: 1, fixed: true }],
      ["4,5", { kind: "mirror", rot: 1 }],
      ["3,5", { kind: "mirror", rot: 1 }],
      ["3,8", { kind: "mirror", rot: 0 }],
      ["7,8", { kind: "target", rot: 0, color: 2, fixed: true }],
      ["4,1", { kind: "mirror", rot: 0 }],
      ["0,1", { kind: "mirror", rot: 1 }],
      ["0,5", { kind: "mirror", rot: 0 }],
      ["2,5", { kind: "target", rot: 0, color: 4, fixed: true }],
      ["7,3", { kind: "emitter", rot: 3, color: 7, fixed: true }],
      ["7,7", { kind: "wall", rot: 0, fixed: true }],
      ["4,6", { kind: "wall", rot: 0, fixed: true }],
    ],
  }),
};

/** Solver-measured facts, recorded at generation time. */
export const GENERATED_FACTS: Record<string, { par: number; solutions: number; score: number }> = {
  "1-4": { par: 2, solutions: 1, score: 55 },
  "1-5": { par: 2, solutions: 1, score: 54 },
  "1-6": { par: 2, solutions: 1, score: 59 },
  "1-7": { par: 3, solutions: 1, score: 70 },
  "1-8": { par: 3, solutions: 1, score: 74 },
  "2-4": { par: 2, solutions: 1, score: 72 },
  "2-5": { par: 2, solutions: 1, score: 57 },
  "2-6": { par: 3, solutions: 1, score: 78 },
  "2-7": { par: 2, solutions: 1, score: 62 },
  "2-8": { par: 3, solutions: 1, score: 80 },
  "2-9": { par: 3, solutions: 3, score: 77 },
  "3-4": { par: 3, solutions: 1, score: 84 },
  "3-5": { par: 3, solutions: 1, score: 92 },
  "3-6": { par: 3, solutions: 3, score: 76 },
  "3-7": { par: 4, solutions: 1, score: 101 },
  "3-8": { par: 4, solutions: 1, score: 94 },
  "3-9": { par: 4, solutions: 1, score: 103 },
  "4-4": { par: 3, solutions: 1, score: 79 },
  "4-5": { par: 4, solutions: 1, score: 95 },
  "4-6": { par: 4, solutions: 1, score: 95 },
  "4-7": { par: 4, solutions: 1, score: 109 },
  "4-8": { par: 5, solutions: 1, score: 126 },
  "4-9": { par: 4, solutions: 1, score: 95 },
  "5-2": { par: 4, solutions: 1, score: 99 },
  "5-3": { par: 4, solutions: 1, score: 94 },
  "5-4": { par: 5, solutions: 1, score: 115 },
  "5-5": { par: 5, solutions: 1, score: 125 },
  "5-6": { par: 5, solutions: 1, score: 120 },
  "6-1": { par: 3, solutions: 1, score: 83 },
  "6-2": { par: 3, solutions: 1, score: 77 },
  "6-3": { par: 3, solutions: 1, score: 79 },
  "6-4": { par: 4, solutions: 1, score: 102 },
  "6-5": { par: 4, solutions: 1, score: 93 },
  "6-6": { par: 5, solutions: 1, score: 125 },
  "7-1": { par: 5, solutions: 1, score: 125 },
  "7-2": { par: 5, solutions: 1, score: 120 },
  "7-3": { par: 5, solutions: 1, score: 115 },
  "7-4": { par: 6, solutions: 1, score: 135 },
  "7-5": { par: 6, solutions: 1, score: 134 },
  "7-6": { par: 5, solutions: 1, score: 125 },
  "7-7": { par: 7, solutions: 1, score: 150 },
  "7-8": { par: 8, solutions: 1, score: 166 },
};
